export const NICHES = [
  { id: "barber", label: "Barbershop", query: "barbershop haircut fade beard", bookingCue: "chair / walk-in / fade" },
  { id: "salon", label: "Hair salon", query: "hair salon color cut highlights", bookingCue: "stylist chair" },
  { id: "tattoo", label: "Tattoo / piercing", query: "tattoo studio piercing shop", bookingCue: "consult / session" },
  { id: "spa", label: "Spa / med-spa", query: "spa massage facial med spa", bookingCue: "treatment room" },
  { id: "nails", label: "Nail salon", query: "nail salon manicure pedicure", bookingCue: "nail tech" },
  { id: "auto", label: "Auto shop", query: "auto repair shop oil change mechanic", bookingCue: "drop-off / bay" },
  { id: "detail", label: "Auto detail", query: "auto detailing ceramic coating", bookingCue: "detail slot" },
  { id: "hvac", label: "HVAC", query: "HVAC heating cooling contractor", bookingCue: "service call" },
  { id: "plumber", label: "Plumber", query: "plumber plumbing company", bookingCue: "service call" },
  { id: "electric", label: "Electrician", query: "electrician electrical contractor", bookingCue: "service call" },
  { id: "lawn", label: "Lawn / landscape", query: "lawn care landscaping company", bookingCue: "estimate / crew day" },
  { id: "photo", label: "Photographer", query: "portrait photographer sessions", bookingCue: "session" },
  { id: "fitness", label: "Trainer / studio", query: "personal trainer fitness studio", bookingCue: "session / class" },
  { id: "vet", label: "Veterinary", query: "veterinary clinic animal hospital", bookingCue: "appointment" },
  { id: "dental", label: "Dental", query: "dentist dental office", bookingCue: "appointment" },
  { id: "foodtruck", label: "Food truck / catering", query: "food truck catering bookings", bookingCue: "event / catering" },
];
